# -*- coding: utf-8 -*-
"""32QAT_MNIST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEJeUJZ7EFAw9kd0WtP8vq7WKE5MPxli
"""

import json
from pathlib import Path
import numpy as np
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

# ===== Helpers (fixed-point / IO) =====
TERNARY_T = 0.7
SHIFT_CONV1 = 15
SHIFT_TERNARY = 6
ROUND_CONV1 = (1 << (SHIFT_CONV1 - 1))
ROUND_TERNARY = (1 << (SHIFT_TERNARY - 1))

# [FIX] RTL 내부 정밀도 정의
CONV2_ACCUM_BITS = 22       # conv2_calc.v: psum_raw (SUM_W) = 22 bits
FC_ACCUM_BITS    = 28       # fc.v: s1 [PROD_W+5:0] -> [27:0] = 28 bits

# 최종 12비트 포화
SAT_MIN = -2048
SAT_MAX = 2047

def q1_15_from_scale(s: float) -> int:
    v = int(np.round(np.clip(float(s), -1.0, (1.0 - 2**-15)) * (1 << 15)))
    return v & 0xFFFF

def q2_6_from_float(x: float) -> int:
    v = int(np.round(np.clip(float(x), -2.0, (2.0 - 2**-6)) * (1 << 6)))
    return v & 0xFF

def int8_twos(x: int) -> int:
    xi = int(x)
    return (xi + (1 << 8)) & 0xFF if xi < 0 else xi & 0xFF

def write_hex_lines(path, values, width_bits):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    fmt = "{:02X}\n" if width_bits == 8 else "{:04X}\n"
    mask = (1 << width_bits) - 1
    with open(path, "w") as f:
        for v in values:
            f.write(fmt.format(int(v) & mask))

# ===== QAT / STE =====
class ArithmeticRightShiftSTE(torch.autograd.Function):
    """ RTL의 (x + R) >>> S (Round-to-nearest-up) 에뮬레이션 + STE """
    @staticmethod
    def forward(ctx, x, shift_bits, round_const):
        divisor = (1 << shift_bits)
        return torch.floor((x + round_const) / divisor)
    @staticmethod
    def backward(ctx, g):
        return g, None, None

class FakeQuantQ2_6STE(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        v = torch.round(torch.clamp(x, -2.0, (2.0 - 2**-6)) * (1 << SHIFT_TERNARY))
        return v
    @staticmethod
    def backward(ctx, g):
        return g

class FakeQuantQ1_15STE(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x_float):
        v = torch.round(torch.clamp(x_float, -1.0, (1.0 - 2**-15)) * (1 << SHIFT_CONV1))
        return v
    @staticmethod
    def backward(ctx, g):
        return g

class ClampSTE(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, min_val, max_val):
        return torch.clamp(x, min_val, max_val)
    @staticmethod
    def backward(ctx, g):
        return g, None, None

# ===== Ternary (QAT with STE) =====
class TernaryQuantFn(torch.autograd.Function):
    @staticmethod
    def forward(ctx, w, delta):
        pos = (w > delta).to(w.dtype)
        neg = (w < -delta).to(w.dtype)
        return pos - neg  # {-1,0,+1}
    @staticmethod
    def backward(ctx, g):
        return g, None

def ternary_with_alpha(w, t=TERNARY_T, per_channel_dim=0):
    dims = list(range(w.dim()))
    red = dims[:]; red.pop(per_channel_dim)
    mean_abs = w.abs().mean(dim=red, keepdim=True)
    delta = t * mean_abs
    tern = TernaryQuantFn.apply(w, delta)
    mask = tern.ne(0).to(w.dtype)
    denom = mask.sum(dim=red, keepdim=True).clamp_min(1.0)
    alpha = (w.abs()*mask).sum(dim=red, keepdim=True)/denom
    return tern, alpha

class TernaryConv2d(nn.Module):
    # conv2_calc.v (SUM_W = 22 bits)
    def __init__(self, in_ch, out_ch, k=5, stride=1, padding=0, t=TERNARY_T, bias=True):
        super().__init__()
        self.weight_fp = nn.Parameter(torch.empty(out_ch, in_ch, k, k))
        self.bias = nn.Parameter(torch.zeros(out_ch)) if bias else None
        self.stride, self.padding, self.t = stride, padding, t
        nn.init.kaiming_normal_(self.weight_fp, nonlinearity='relu')
        self.ACC_MAX = (1 << (CONV2_ACCUM_BITS - 1)) - 1
        self.ACC_MIN = -(1 << (CONV2_ACCUM_BITS - 1))

    def forward(self, x):
        # x shape: (N, C_in=3, H_in, W_in)
        tern_w, alpha_f = ternary_with_alpha(self.weight_fp, t=self.t, per_channel_dim=0)
        # tern_w shape: (C_out=3, C_in=3, 5, 5)

        # --- [FIX] Emulate RTL's 3 separate Adder Trees (AT1, AT2, AT3) ---
        psum_f32 = 0.0
        for ic in range(x.size(1)): # C_in=3
            # 1. 1-channel convolution (emulates one Adder Tree)
            # x[:, ic:ic+1] -> (N, 1, H, W)
            # tern_w[:, ic:ic+1] -> (C_out, 1, 5, 5)
            # groups=C_out (Depthwise) ensures C_out filters apply to C_in=1
            # We must simulate C_out convolutions, each on 1 input channel

            # This is complex. Let's simplify:
            # F.conv2d(x_in, w_in) does sum(x_ic * w_oc_ic)
            # We need sum( clamp(x1*w1, 22b) + clamp(x2*w2, 22b) + clamp(x3*w3, 22b) )

            # F.conv2d(x, tern_w, ...) already calculates sum(x_ic * w_oc_ic)
            # What RTL does is sum_ic( AdderTree(x_ic * w_oc_ic) )
            # The AdderTree(x*w) clamps the sum of 25 products to 22 bits.

            # Let's emulate sum1, sum2, sum3
            # x_ic: (N, 1, H_in, W_in)
            x_ic = x[:, ic:ic+1, ...]

            # w_oc_ic: (C_out, 1, 5, 5)
            w_oc_ic = tern_w[:, ic:ic+1, ...].to(x.dtype)

            # sum_ic = F.conv2d(x_ic, w_oc_ic)
            # This isn't right. F.conv2d(N,1,H,W) with (C_out,1,K,K) is what we need.

            sum_ic_f32 = F.conv2d(x_ic, w_oc_ic, bias=None, stride=self.stride, padding=self.padding)

            # 2. [FIX] Clamp each input channel's sum to 22-bits (emulating sum1, sum2, sum3)
            sum_ic_clamped = ClampSTE.apply(sum_ic_f32, self.ACC_MIN, self.ACC_MAX)

            # 3. Add to total psum_raw
            psum_f32 = psum_f32 + sum_ic_clamped

        # y_acc is psum_raw. This final sum can exceed 22 bits, which is fine.
        y_acc = psum_f32
        # --- End of RTL Emulation ---

        # 3. RTL QAT (Scaling, Bias, Shift)
        alpha_q = FakeQuantQ2_6STE.apply(alpha_f).view(1, -1, 1, 1)
        bias_q  = FakeQuantQ2_6STE.apply(self.bias).view(1, -1, 1, 1)

        # 4. RTL 시프트 연산 (STE)
        s = ArithmeticRightShiftSTE.apply(y_acc * alpha_q, SHIFT_TERNARY, ROUND_TERNARY)
        b = ArithmeticRightShiftSTE.apply(bias_q, SHIFT_TERNARY, ROUND_TERNARY)

        # 5. 덧셈 및 12-bit 포화
        y = torch.clamp(s + b, SAT_MIN, SAT_MAX)
        return y

    @torch.no_grad()
    def export(self):
        tern, alpha = ternary_with_alpha(self.weight_fp, t=self.t, per_channel_dim=0)
        a = alpha[:,0,0,0]
        return tern.cpu().to(torch.int8), a.cpu().to(torch.float32)

class TernaryLinear(nn.Module):
    # fc.v: s1 (PROD_W+5:0) = 28 bits
    def __init__(self, in_f, out_f, t=TERNARY_T, bias=True):
        super().__init__()
        self.weight_fp = nn.Parameter(torch.empty(out_f, in_f))
        self.bias = nn.Parameter(torch.zeros(out_f)) if bias else None
        self.t = t
        nn.init.kaiming_uniform_(self.weight_fp, a=np.sqrt(5))
        self.ACC_MAX = (1 << (FC_ACCUM_BITS - 1)) - 1
        self.ACC_MIN = -(1 << (FC_ACCUM_BITS - 1))

    def forward(self, x):
        tern_w, alpha_f = ternary_with_alpha(self.weight_fp, t=self.t, per_channel_dim=0)
        y_acc_f32 = F.linear(x, tern_w.to(x.dtype), bias=None)
        y_acc = ClampSTE.apply(y_acc_f32, self.ACC_MIN, self.ACC_MAX)
        alpha_q = FakeQuantQ2_6STE.apply(alpha_f[:,0]).view(1, -1)
        bias_q  = FakeQuantQ2_6STE.apply(self.bias).view(1, -1)
        s = ArithmeticRightShiftSTE.apply(y_acc * alpha_q, SHIFT_TERNARY, ROUND_TERNARY)
        b = ArithmeticRightShiftSTE.apply(bias_q, SHIFT_TERNARY, ROUND_TERNARY)
        y = torch.clamp(s + b, SAT_MIN, SAT_MAX)
        return y

    @torch.no_grad()
    def export(self):
        tern, alpha = ternary_with_alpha(self.weight_fp, t=self.t, per_channel_dim=0)
        return tern.cpu().to(torch.int8), alpha[:,0].cpu().to(torch.float32)

# ===== conv1: INT8 QAT wrapper (flip 지원) =====
class Int8PerOCConv2d_QAT(nn.Module):
    def __init__(self, in_ch, out_ch, k=5, stride=1, padding=0, bias=True, flip=True):
        super().__init__()
        self.weight_fp = nn.Parameter(torch.empty(out_ch, in_ch, k, k))
        self.bias = nn.Parameter(torch.zeros(out_ch)) if bias else None
        self.stride, self.padding = stride, padding
        self.flip = flip
        nn.init.kaiming_normal_(self.weight_fp, nonlinearity='relu')

    def _maybe_flip(self, w):
        if not self.flip: return w
        return torch.flip(w, dims=[-1, -2])

    def forward(self, x):
        w_flipped = self._maybe_flip(self.weight_fp)
        qW_list, S_q1_15_list = [], []
        for oc in range(w_flipped.size(0)):
            w_oc = w_flipped[oc]
            max_abs_val = w_oc.abs().max().clamp(min=1e-12)
            inv_s_tensor = max_abs_val / 127.0   # RTL dequant scale
            S_q1_15_oc = FakeQuantQ1_15STE.apply(inv_s_tensor)
            S_q1_15_list.append(S_q1_15_oc)
            quant_scale_s = 127.0 / max_abs_val
            qW_oc = torch.clamp(torch.round(w_oc * quant_scale_s), -128, 127)
            qW_oc_ste = (qW_oc - w_oc).detach() + w_oc
            qW_list.append(qW_oc_ste)
        qW_ste = torch.stack(qW_list, dim=0)
        S_q1_15_ste = torch.stack(S_q1_15_list, dim=0).view(1, -1, 1, 1)

        # bias: int8 (스케일 없이 더함)
        bias_int8 = torch.round(torch.clamp(self.bias, -128, 127))
        bias_q_ste = (bias_int8 - self.bias).detach() + self.bias
        bias_q_ste = bias_q_ste.view(1, -1, 1, 1)

        y_acc = F.conv2d(x, qW_ste.to(x.dtype), bias=None, stride=self.stride, padding=self.padding)
        s = ArithmeticRightShiftSTE.apply(y_acc * S_q1_15_ste, SHIFT_CONV1, ROUND_CONV1)
        y = torch.clamp(s + bias_q_ste, SAT_MIN, SAT_MAX)
        return y

    @torch.no_grad()
    def export(self):
        w = self._maybe_flip(self.weight_fp.detach().cpu())
        oc, ic, k, _ = w.shape
        qW_export = torch.empty_like(w, dtype=torch.int8)
        scales_q1_15_u16_export = []
        for o in range(oc):
            m = w[o].abs().max().item()
            s = 127.0 / (m + 1e-12)
            q = torch.clamp(torch.round(w[o] * s), -128, 127).to(torch.int8)
            inv_s = 1.0 / s
            qW_export[o] = q
            scales_q1_15_u16_export.append(q1_15_from_scale(inv_s))
        b_int8_export = torch.clamp(torch.round(self.bias.detach().cpu()), -128, 127).to(torch.int32)
        return qW_export, scales_q1_15_u16_export, b_int8_export

# ===== Net (28→24→pool→12→8→pool→4; 3*4*4=48 → FC10) =====
class Net(nn.Module):
    def __init__(self, t=TERNARY_T):
        super().__init__()
        self.conv1 = Int8PerOCConv2d_QAT(1, 3, 5, bias=True, flip=True)
        self.conv2 = TernaryConv2d(3, 3, 5, t=t, bias=True)
        self.pool  = nn.MaxPool2d(2)
        self.fc    = TernaryLinear(48, 10, t=t, bias=True)
    def forward(self, x):
        x = x * 255.0
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(x.size(0), -1)
        return self.fc(x)

# ===== Train / Eval =====
def get_loaders(batch, workers, data_dir):
    tfm = transforms.Compose([transforms.ToTensor()])
    tr = datasets.MNIST(data_dir, train=True,  download=True, transform=tfm)
    te = datasets.MNIST(data_dir, train=False, download=True, transform=tfm)
    return (DataLoader(tr, batch_size=batch, shuffle=True,  num_workers=workers, pin_memory=True),
            DataLoader(te, batch_size=512,  shuffle=False, num_workers=workers, pin_memory=True))

def train_one_epoch(net, loader, opt, device):
    net.train(); ce = nn.CrossEntropyLoss()
    tot=0; corr=0; loss_sum=0.0
    for x,y in loader:
        x,y = x.to(device), y.to(device)
        opt.zero_grad(set_to_none=True)
        logit = net(x)
        loss = ce(logit,y); loss.backward(); opt.step()
        loss_sum += loss.item()*x.size(0)
        corr += (logit.argmax(1)==y).sum().item(); tot += x.size(0)
    return loss_sum/tot, corr/tot

@torch.no_grad()
def evaluate(net, loader, device):
    net.eval(); ce=nn.CrossEntropyLoss()
    tot=0; corr=0; loss_sum=0.0
    for x,y in loader:
        x,y = x.to(device), y.to(device)
        logit = net(x); loss = ce(logit,y)
        loss_sum += loss.item()*x.size(0)
        corr += (logit.argmax(1)==y).sum().item(); tot += x.size(0)
    return loss_sum/tot, corr/tot

# ===== Export helpers =====
@torch.no_grad()
def export_txt_from_model(model: Net, outdir="weights_txt", fc_order="CHW"):
    out = Path(outdir); out.mkdir(parents=True, exist_ok=True)

    # conv1: INT8 per-OC + inv_scale(Q1.15)
    qW1, S1_u16, b1_int8 = model.conv1.export()
    qW1 = qW1.squeeze(1).numpy()
    names_c1 = ["conv1_weight_1.txt","conv1_weight_2.txt","conv1_weight_3.txt"]
    for oc, fname in enumerate(names_c1):
        vals = qW1[oc].reshape(-1).tolist()
        write_hex_lines(out/fname, [int8_twos(int(v)) for v in vals], 8)
    write_hex_lines(out/"conv1_bias.txt",  [int8_twos(int(v)) for v in b1_int8.tolist()], 8)
    write_hex_lines(out/"conv1_scale.txt", [int(x) for x in S1_u16], 16)

    # conv2 (ternary + alpha/bias Q2.6)
    t2_w, t2_a = model.conv2.export()
    w2 = t2_w.numpy(); a2 = t2_a.numpy()
    names = [
        ["conv2_weight_11.txt","conv2_weight_12.txt","conv2_weight_13.txt"],
        ["conv2_weight_21.txt","conv2_weight_22.txt","conv2_weight_23.txt"],
        ["conv2_weight_31.txt","conv2_weight_32.txt","conv2_weight_33.txt"],
    ]
    for oc in range(3):
        for ic in range(3):
            write_hex_lines(out/names[oc][ic],
                            [int8_twos(int(v)) for v in w2[oc,ic].reshape(-1).tolist()], 8)
    b2 = model.conv2.bias.detach().cpu().numpy()
    write_hex_lines(out/"conv2_alpha.txt", [q2_6_from_float(float(x)) for x in a2.tolist()], 8)
    write_hex_lines(out/"conv2_bias.txt",  [q2_6_from_float(float(x)) for x in b2.tolist()], 8)

    # FC (ternary + alpha/bias Q2.6)
    t_fc, a_fc = model.fc.export()
    wfc = t_fc.numpy(); afc = a_fc.numpy()

    # RTL FSM: CHW 플래튼 순서
    if fc_order.upper() == "CHW":
        seq=[]
        for k in range(10):
            seq.extend(wfc[k].reshape(-1).tolist())
    else:
        raise ValueError(f"FC order {fc_order} not supported by RTL FSM. Use CHW.")

    write_hex_lines(out/"fc_weight.txt", [int8_twos(int(v)) for v in seq], 8)
    bfc = model.fc.bias.detach().cpu().numpy()
    write_hex_lines(out/"fc_scale.txt", [q2_6_from_float(float(x)) for x in afc.tolist()], 8)
    write_hex_lines(out/"fc_bias.txt",  [q2_6_from_float(float(x)) for x in bfc.tolist()], 8)

    (out/"manifest.json").write_text(json.dumps({
        "note": "All txt files are $readmemh-compatible (one hex per line).",
        "conv1_scale_q1_15_u16": [int(x) for x in S1_u16]
    }, indent=2), encoding="utf-8")
    print(f"[OK] wrote txt weights under: {out}")

# ===== Debug helpers =====
@torch.no_grad() # [FIX] SyntaxError: no_grad__() -> no_grad()
def dump_fc_boundary_and_logits(model: Net, device, save_dir="runs/debug_dump"):
    p = Path(save_dir); p.mkdir(parents=True, exist_ok=True)
    model.eval()
    tfm = transforms.Compose([transforms.ToTensor()])
    ds = datasets.MNIST('./data', train=False, download=True, transform=tfm)
    x0 = ds[0][0].unsqueeze(0).to(device)   # [1,1,28,28]
    y0 = ds[0][1]

    x = x0 * 255.0
    c1 = model.conv1(x); c1 = torch.clamp(c1, SAT_MIN, SAT_MAX) # QAT 모듈이 이미 clamp함
    c1 = F.relu(c1)
    p1 = model.pool(c1)             # [1,3,12,12]

    c2 = model.conv2(p1); c2 = torch.clamp(c2, SAT_MIN, SAT_MAX) # QAT 모듈이 이미 clamp함
    c2 = F.relu(c2)
    p2 = model.pool(c2)             # [1,3,4,4]

    feat = p2.view(48).to('cpu').to(torch.int16).numpy()
    (p/"fc_input_chw.txt").write_text("\n".join(str(int(v)) for v in feat), encoding="utf-8")

    logits = model.fc(p2.view(1,-1)).squeeze(0).to('cpu').to(torch.int16).numpy()
    (p/"fc_logits_py.txt").write_text("\n".join(str(int(v)) for v in logits), encoding="utf-8")

    print(f"[DUMP] FC 입력(48) -> {p/'fc_input_chw.txt'}")
    print(f"[DUMP] 파이토치 로짓(10) -> {p/'fc_logits_py.txt'}")
    print(f"[INFO] label={y0}")

@torch.no_grad()
def reeval_fc_from_txt(save_dir="runs/mnist_twn_qat_v4_precision/weights_txt",
                       fc_input_path="runs/debug_dump/fc_input_chw.txt"):
    import numpy as np
    sd = Path(save_dir)
    w_txt = sd/"fc_weight.txt"
    s_txt = sd/"fc_scale.txt"
    b_txt = sd/"fc_bias.txt"

    feat = np.loadtxt(fc_input_path, dtype=np.int32)        # 48
    whex = [int(line.strip(), 16) for line in w_txt.read_text().splitlines()]  # 10*48
    shex = [int(line.strip(), 16) for line in s_txt.read_text().splitlines()]  # 10
    bhex = [int(line.strip(), 16) for line in b_txt.read_text().splitlines()]  # 10

    def int8_from_hex(v):
        v &= 0xFF
        return v-256 if v>=128 else v

    W = np.array([int8_from_hex(v) for v in whex], dtype=np.int32).reshape(10, 48)
    S = np.array([int8_from_hex(v) for v in shex], dtype=np.int32)   # alpha Q2.6
    B = np.array([int8_from_hex(v) for v in bhex], dtype=np.int32)   # bias  Q2.6

    Wt = np.clip(W, -1, 1)

    # [FIX] RTL FC 누적 정밀도(28-bit) 반영
    acc_max = (1 << (FC_ACCUM_BITS - 1)) - 1
    acc_min = -(1 << (FC_ACCUM_BITS - 1))
    psum_f32 = (Wt * feat[None,:]).sum(axis=1).astype(np.int64)
    psum = np.clip(psum_f32, acc_min, acc_max)

    alpha = S.astype(np.int64)
    bias  = B.astype(np.int64)

    # RTL 라운딩 (Round-half-up)
    scaled = (psum * alpha + ROUND_TERNARY) >> SHIFT_TERNARY
    bias_i = (bias + ROUND_TERNARY) >> SHIFT_TERNARY

    out = scaled + bias_i
    out = np.clip(out, SAT_MIN, SAT_MAX).astype(np.int32)

    Path("runs/debug_dump").mkdir(parents=True, exist_ok=True)
    Path("runs/debug_dump/fc_logits_txt.txt").write_text(
        "\n".join(str(int(v)) for v in out), encoding="utf-8"
    )
    print("[CHECK] txt기반 로짓(10) -> runs/debug_dump/fc_logits_txt.txt")

# ===== Main (Colab-friendly, no argparse) =====
def main():
    class Args:
        epochs = 20
        batch = 128
        lr = 1e-3
        t = TERNARY_T
        workers = 2
        data = './data'
        out = 'runs/mnist_twn_qat_v4_precision'
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
        export_only = False
        ckpt = ''
        flip_off = True      # RTL cross-correlation 정합용
        fc_order = 'CHW'
        # 디버그 옵션
        do_dump = False      # True면 FC 경계/로짓 덤프
        do_reeval = False    # True면 텍스트 가중치로 재평가

    args = Args()

    torch.backends.cudnn.benchmark = True
    device = torch.device(args.device)
    net = Net(t=args.t).to(device)

    if args.flip_off and isinstance(net.conv1, Int8PerOCConv2d_QAT):
        net.conv1.flip = False
        print("[Config] conv1 kernel flip DISABLED (RTL cross-correlation mode)")

    outdir = Path(args.out); outdir.mkdir(parents=True, exist_ok=True)
    ckpt_best = outdir/'mnist_ternary_best.pth'

    if args.export_only:
        ckpt_path = Path(args.ckpt) if args.ckpt else ckpt_best
        sd = torch.load(ckpt_path, map_location=device)
        net.load_state_dict(sd)
        export_txt_from_model(net, outdir=str(outdir/'weights_txt'), fc_order=args.fc_order)
        if args.do_dump:
            dump_fc_boundary_and_logits(net, device, save_dir="runs/debug_dump")
        if args.do_reeval:
            reeval_fc_from_txt(save_dir=str(outdir/'weights_txt'),
                               fc_input_path="runs/debug_dump/fc_input_chw.txt")
        return

    # train
    tr, te = get_loaders(args.batch, args.workers, args.data)
    opt = torch.optim.Adam(net.parameters(), lr=args.lr)
    best = 0.0
    for ep in range(1, args.epochs+1):
        tl, ta = train_one_epoch(net, tr, opt, device)
        vl, va = evaluate(net, te, device)
        print(f"[Ep {ep:02d}] train {tl:.4f}/{ta*100:.2f}% | test {vl:.4f}/{va*100:.2f}%")
        if va > best:
            best = va
            torch.save(net.state_dict(), ckpt_best)
    torch.save(net.state_dict(), outdir/'mnist_ternary_last.pth')
    print(f"[DONE] best acc {best*100:.2f}%, ckpt: {ckpt_best}")

    # export from best
    sd = torch.load(ckpt_best, map_location=device)
    net.load_state_dict(sd)
    export_txt_from_model(net, outdir=str(outdir/'weights_txt'), fc_order=args.fc_order)

    if args.do_dump:
        dump_fc_boundary_and_logits(net, device, save_dir="runs/debug_dump")
    if args.do_reeval:
        reeval_fc_from_txt(save_dir=str(outdir/'weights_txt'),
                           fc_input_path="runs/debug_dump/fc_input_chw.txt")

if __name__ == "__main__":
    main()

# 올바른 경로 (v4_precision)
directory_to_zip = 'content/weights_output'

import shutil, os
assert os.path.isdir(directory_to_zip), f"경로 없음: {directory_to_zip}"

zip_base = 'SH'  # 원하는 파일명
shutil.make_archive(
    base_name=zip_base,
    format='zip',
    root_dir=os.path.dirname(directory_to_zip),
    base_dir=os.path.basename(directory_to_zip)
)
print("ZIP 생성:", os.path.abspath(zip_base + '.zip'))

from google.colab import files
files.download(zip_base + '.zip')

import torch, json
from pathlib import Path

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# 모델 로드 (경로는 당신 스크립트와 동일)
net = Net().to(device)
ckpt = torch.load('runs/mnist_twn_qat_v4_precision/mnist_ternary_best.pth', map_location=device)
net.load_state_dict(ckpt)

# conv1 커널 뒤집기 비활성화가 훈련/추론 둘다 동일해야 합니다.
if isinstance(net.conv1, Int8PerOCConv2d_QAT):
    net.conv1.flip = False

dump_fc_boundary_and_logits(net, device, save_dir="runs/debug_dump")

import numpy as np
from pathlib import Path

# ====== 경로 ======
# [!] 훈련된 가중치가 있는 경로로 수정하세요
WDIR = Path("runs/mnist_twn_qat_v4_precision")
# [!] conv1의 입력 이미지가 있는 경로로 수정하세요
IN_DIR = Path("runs")
OUT_DIR = Path("runs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# conv1 weight files (각 25개, int8 2's comp HEX)
W_FILES = [
    WDIR/"conv1_weight_1.txt",  # OC=1
    WDIR/"conv1_weight_2.txt",  # OC=2
    WDIR/"conv1_weight_3.txt",  # OC=3
]
SCALE_P = WDIR/"conv1_scale.txt"   # 3줄, Q1.15 (16-bit 2's comp HEX)
BIAS_P  = WDIR/"conv1_bias.txt"    # 3줄, Int8 2's comp HEX

# [!] conv1 입력 (원본 이미지, 28x28, 8-bit *unsigned* HEX)
#     - 00, 01, ..., FF
IMAGE_P = IN_DIR/"00_input_u8_28x28.txt"

# 출력 파일 (24x24, 12-bit 2's comp HEX)
O1 = OUT_DIR/"conv1_out_ch1_24x24_12b.hex"
O2 = OUT_DIR/"conv1_out_ch2_24x24_12b.hex"
O3 = OUT_DIR/"conv1_out_ch3_24x24_12b.hex"

# ====== 헬퍼 ======
def read_hex8_signed(path, n=None):
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFF
            if v >= 128: v -= 256
            vals.append(v)
    return np.array(vals if n is None else vals[:n], dtype=np.int32)

def read_hex16_signed(path, n=None):
    """ conv1_scale.txt (Q1.15)용 16비트 signed 리더 """
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFFFF
            if v >= 0x8000: v -= 0x10000 # 16-bit 2's complement
            vals.append(v)
    return np.array(vals if n is None else vals[:n], dtype=np.int32)

def read_hex8_unsigned(path, wh=None):
    """ conv1 입력 이미지 (8-bit unsigned)용 리더 """
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFF # 0-255
            vals.append(v)
    a = np.array(vals, dtype=np.int32)
    if wh is not None:
        H,W = wh
        assert a.size == H*W, f"Expected {H}x{W}, got {a.size}"
        a = a.reshape(H,W)
    return a

def write_hex12_2s(path, arr_hw):
    with open(path, "w") as f:
        for v in arr_hw.reshape(-1):
            v = int(np.clip(v, -2048, 2047))
            if v < 0: v = (v + (1<<12)) & 0xFFF
            f.write(f"{v:03X}\n")

def im2col5x5_stride1(img):
    # img: HxW (28x28) -> (24*24, 25)
    H,W = img.shape
    out=[]
    OH = H - 5 + 1
    OW = W - 5 + 1
    for y in range(OH):        # 0..23
        for x in range(OW):    # 0..23
            patch = img[y:y+5, x:x+5].reshape(-1).astype(np.int32)
            out.append(patch)
    return np.stack(out, axis=0)      # (576, 25)

def q15_round_shift(x_int):
    # (x + 16384) >> 15  (ROUND_CONV1 = 1 << (15-1) = 16384)
    return (x_int + 16384) >> 15

def sat12_np(a):
    return np.clip(a, -2048, 2047).astype(np.int32)

# ====== 입력 로드 (28x28) ======
img_in = read_hex8_unsigned(IMAGE_P, wh=(28,28))

# ====== 5x5 패치 (stride=1) ======
# RTL의 conv1_buf 역할 수행
cols = im2col5x5_stride1(img_in)   # (576, 25)

# ====== conv1 가중치/스케일/바이어스 로드 ======
# W[oc] -> (25,)
W = []
for oc in range(3):
    W.append(read_hex8_signed(W_FILES[oc], n=25)) # conv1은 IC=1

scales_q15  = read_hex16_signed(SCALE_P, n=3) # int16 raw, Q1.15
biases_int8 = read_hex8_signed(BIAS_P,  n=3)  # int8 raw, (스케일링 안 됨)

# ====== conv1 연산 (RTL 정수 경로 그대로) ======
outs = []
for oc in range(3):
    w = W[oc] # (25,)

    # psum = sum(cols_ic @ w_ic)
    # RTL[cite: 612]: 8-bit unsigned (0-255) 입력을 9-bit signed로 zero-extend
    # Numpy (np.int32 @ np.int32)는 동일한 결과를 줌
    psum = (cols.astype(np.int32) @ w.astype(np.int32)).astype(np.int64) # (576,)

    # [FIX] RTL conv1 로직: ( (psum*scale)>>15 ) + bias_int8
    scale = int(scales_q15[oc])
    bias  = int(biases_int8[oc])

    scaled = q15_round_shift(psum * scale)     # (576,)
    b_int  = np.int64(bias)                    # 스칼라

    y = sat12_np(scaled + b_int).reshape(24, 24)
    outs.append(y)

# ====== 저장 ======
write_hex12_2s(O1, outs[0])
write_hex12_2s(O2, outs[1])
write_hex12_2s(O3, outs[2])

print("[OK] conv1 outputs saved:")
print(" -", O1)
print(" -", O2)
print(" -", O3)
print("\n[INFO] 28x28 입력 파일:", IMAGE_P)

import numpy as np
from pathlib import Path

# ====== 경로 ======
# [!] 훈련된 가중치가 있는 경로로 수정하세요
WDIR = Path("runs/mnist_twn_qat_v4_precision")
# [!] conv1의 입력 이미지가 있는 경로로 수정하세요
IN_DIR = Path("runs")
OUT_DIR = Path("runs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# conv1 weight files (각 25개, int8 2's comp HEX)
W_FILES = [
    WDIR/"conv1_weight_1.txt",  # OC=1
    WDIR/"conv1_weight_2.txt",  # OC=2
    WDIR/"conv1_weight_3.txt",  # OC=3
]
SCALE_P = WDIR/"conv1_scale.txt"   # 3줄, Q1.15 (16-bit 2's comp HEX)
BIAS_P  = WDIR/"conv1_bias.txt"    # 3줄, Int8 2's comp HEX

# [!] conv1 입력 (원본 이미지, 28x28, 8-bit *unsigned* HEX)
#     - 00, 01, ..., FF
IMAGE_P = IN_DIR/"00_input_u8_28x28.txt"

# conv1 출력 파일 (24x24, 12-bit 2's comp HEX)
O1_CONV1 = OUT_DIR/"conv1_out_ch1_24x24_12b.hex"
O2_CONV1 = OUT_DIR/"conv1_out_ch2_24x24_12b.hex"
O3_CONV1 = OUT_DIR/"conv1_out_ch3_24x24_12b.hex"

# [!] pool1 출력 파일 (12x12, 12-bit 2's comp HEX)
O1_POOL1 = OUT_DIR/"pool1_out_ch1_12x12_12b.hex"
O2_POOL1 = OUT_DIR/"pool1_out_ch2_12x12_12b.hex"
O3_POOL1 = OUT_DIR/"pool1_out_ch3_12x12_12b.hex"

# ====== 헬퍼 ======
def read_hex8_signed(path, n=None):
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFF
            if v >= 128: v -= 256
            vals.append(v)
    return np.array(vals if n is None else vals[:n], dtype=np.int32)

def read_hex16_signed(path, n=None):
    """ conv1_scale.txt (Q1.15)용 16비트 signed 리더 """
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFFFF
            if v >= 0x8000: v -= 0x10000 # 16-bit 2's complement
            vals.append(v)
    return np.array(vals if n is None else vals[:n], dtype=np.int32)

def read_hex8_unsigned(path, wh=None):
    """ conv1 입력 이미지 (8-bit unsigned)용 리더 """
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFF # 0-255
            vals.append(v)
    a = np.array(vals, dtype=np.int32)
    if wh is not None:
        H,W = wh
        assert a.size == H*W, f"Expected {H}x{W}, got {a.size}"
        a = a.reshape(H,W)
    return a

def write_hex12_2s(path, arr_hw):
    with open(path, "w") as f:
        for v in arr_hw.reshape(-1):
            v = int(np.clip(v, -2048, 2047))
            if v < 0: v = (v + (1<<12)) & 0xFFF
            f.write(f"{v:03X}\n")

def im2col5x5_stride1(img):
    # img: HxW (28x28) -> (24*24, 25)
    H,W = img.shape
    out=[]
    OH = H - 5 + 1
    OW = W - 5 + 1
    for y in range(OH):        # 0..23
        for x in range(OW):    # 0..23
            patch = img[y:y+5, x:x+5].reshape(-1).astype(np.int32)
            out.append(patch)
    return np.stack(out, axis=0)      # (576, 25)

def q15_round_shift(x_int):
    # (x + 16384) >> 15  (ROUND_CONV1 = 1 << (15-1) = 16384)
    return (x_int + 16384) >> 15

def sat12_np(a):
    return np.clip(a, -2048, 2047).astype(np.int32)

def maxpool2x2_relu(img_in):
    """ [NEW] maxpool_relu.v 에뮬레이션 """
    # img_in: HxW (24x24)
    H, W = img_in.shape
    OH, OW = H // 2, W // 2 # 12, 12
    out = np.zeros((OH, OW), dtype=np.int32)

    for y in range(OH):
        for x in range(OW):
            y_in, x_in = y * 2, x * 2
            # 1. 2x2 Max Pooling (signed)
            patch = img_in[y_in:y_in+2, x_in:x_in+2]
            max_val = np.max(patch)

            # 2. ReLU (signed-safe)
            out[y, x] = max_val if max_val > 0 else 0

    return out

# ====== 입력 로드 (28x28) ======
img_in = read_hex8_unsigned(IMAGE_P, wh=(28,28))

# ====== 5x5 패치 (stride=1) ======
cols = im2col5x5_stride1(img_in)   # (576, 25)

# ====== conv1 가중치/스케일/바이어스 로드 ======
W = []
for oc in range(3):
    W.append(read_hex8_signed(W_FILES[oc], n=25)) # conv1은 IC=1

scales_q15  = read_hex16_signed(SCALE_P, n=3) # int16 raw, Q1.15
biases_int8 = read_hex8_signed(BIAS_P,  n=3)  # int8 raw, (스케일링 안 됨)

# ====== conv1 연산 (RTL 정수 경로 그대로) ======
conv1_outs = []
for oc in range(3):
    w = W[oc] # (25,)
    psum = (cols.astype(np.int32) @ w.astype(np.int32)).astype(np.int64) # (576,)

    scale = int(scales_q15[oc])
    bias  = int(biases_int8[oc])

    scaled = q15_round_shift(psum * scale)     # (576,)
    b_int  = np.int64(bias)                    # 스칼라

    y = sat12_np(scaled + b_int).reshape(24, 24)
    conv1_outs.append(y)


# ====== [NEW] pool1 연산 (MaxPool + ReLU) ======
pool1_outs = []
for oc in range(3):
    # conv1_outs[oc]는 (24, 24)
    pool_out = maxpool2x2_relu(conv1_outs[oc]) # (12, 12)
    pool1_outs.append(pool_out)

# ====== pool1 출력 저장 ======
write_hex12_2s(O1_POOL1, pool1_outs[0])
write_hex12_2s(O2_POOL1, pool1_outs[1])
write_hex12_2s(O3_POOL1, pool1_outs[2])

print("\n[OK] pool1 outputs (12x12) saved:")
print(" -", O1_POOL1)
print(" -", O2_POOL1)
print(" -", O3_POOL1)

print("\n[INFO] 28x28 입력 파일:", IMAGE_P)

import numpy as np
from pathlib import Path

# ====== 경로 ======
# [!] 훈련된 가중치가 있는 경로로 수정하세요
WDIR = Path("runs/mnist_twn_qat_v4_precision")
# [!] conv2의 96-cycle 출력이 저장된 경로로 수정하세요
IN_DIR = Path("runs")  # conv2_out_ch*_96_cycles_12b.hex 가 여기 있음
OUT_DIR = IN_DIR
OUT_DIR.mkdir(parents=True, exist_ok=True)

# [FIX] conv2 입력 (RTL 96-cycle 파형, 12-bit HEX)
C1_IN_96 = IN_DIR/"conv2_out_ch1_96_cycles_12b.hex"
C2_IN_96 = IN_DIR/"conv2_out_ch2_96_cycles_12b.hex"
C3_IN_96 = IN_DIR/"conv2_out_ch3_96_cycles_12b.hex"

# pool2 출력 파일 (4x4, 12-bit 2's comp HEX)
O1_POOL2 = OUT_DIR/"pool2_out_ch1_4x4_12b.hex"
O2_POOL2 = OUT_DIR/"pool2_out_ch2_4x4_12b.hex"
O3_POOL2 = OUT_DIR/"pool2_out_ch3_4x4_12b.hex"

# ====== 헬퍼 ======
def read_hex12_signed(path, n=None):
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFFF
            if v >= 0x800: v -= 0x1000
            vals.append(v)
            if n is not None and len(vals) >= n:
                break
    a = np.array(vals, dtype=np.int32)
    if n is not None:
        assert a.size == n, f"Expected {n} values, got {a.size}"
    return a

def write_hex12_2s(path, arr_hw):
    with open(path, "w") as f:
        for v in arr_hw.reshape(-1):
            v = int(np.clip(v, -2048, 2047))
            if v < 0: v = (v + (1<<12)) & 0xFFF
            f.write(f"{v:03X}\n")

def rtl_fsm_maxpool_relu(stream_in_96):
    """
    [FIX] maxpool_relu.v FSM을 사이클 단위로 1:1 에뮬레이션
    "8-valid, 4-invalid" (총 12개) 스트림 8줄을 입력받아 4x4 출력 생성
    """
    HALF_WIDTH = 4 # u_pool2의 HALF_WIDTH=4
    buffer1 = np.zeros(HALF_WIDTH, dtype=np.int32)

    pcount = 0
    state = 0 # 0 = row 0, 1 = row 1
    flag = 0  # 0 = col 0, 1 = col 1

    # "8-valid, 4-invalid" 96-cycle valid 스트림 생성
    valid_stream = []
    for i in range(8): # 8줄
        valid_stream.extend([1] * 8) # 8-valid
        valid_stream.extend([0] * 4) # 4-invalid

    outputs = []

    # 96 사이클 전체를 순회
    for i in range(96):
        valid_in = valid_stream[i]
        conv_out_1 = stream_in_96[i]

        # RTL의 always @(posedge clk)에 해당

        if valid_in == 1:
            # Verilog의 non-blocking 할당(<=)을 위해,
            # 이번 사이클 계산에는 *이전* 사이클의 FSM 상태값을 사용합니다.
            current_flag = flag
            current_pcount = pcount
            current_state = state

            # --- 1. 다음 상태(Next State) 계산 ---
            # flag <= ~flag;
            next_flag = 1 - current_flag

            next_pcount = current_pcount
            next_state = current_state

            # if(flag == 1)
            if current_flag == 1: # 2번째 또는 4번째 입력이 들어온 사이클
                # pcount <= pcount + 1;
                next_pcount = current_pcount + 1
                # if(pcount == HALF_WIDTH - 1)
                if next_pcount == HALF_WIDTH:
                    next_pcount = 0
                    # state <= ~state;
                    next_state = 1 - current_state

            # --- 2. 현재 상태(Current State)로 연산 수행 ---

            # if(state == 0)
            if current_state == 0: # First line
                # if(flag == 0)
                if current_flag == 0: # 1st input
                    buffer1[current_pcount] = conv_out_1
                else: # 2nd input -> comparison
                    if buffer1[current_pcount] < conv_out_1:
                        buffer1[current_pcount] = conv_out_1

            # else (state == 1)
            else: # Second line
                # if(flag == 0)
                if current_flag == 0: # 3rd input
                    if buffer1[current_pcount] < conv_out_1:
                        buffer1[current_pcount] = conv_out_1
                else: # 4th input -> comparison + relu
                    # valid_out_relu <= 1;

                    # Max(buffer, conv_out)
                    temp_max = conv_out_1 if buffer1[current_pcount] < conv_out_1 else buffer1[current_pcount]

                    # ReLU (signed-safe: 0보다 작으면 0)
                    relu_out = temp_max if temp_max > 0 else 0
                    outputs.append(relu_out)

            # --- 3. FSM 상태 업데이트 (다음 클럭을 위해) ---
            flag = next_flag
            pcount = next_pcount
            state = next_state

        # if (valid_in == 0):
        #   FSM이 "얼어붙습니다". flag, pcount, state가 변하지 않습니다.
        #   NumPy 루프는 다음 사이클(i+1)로 넘어갑니다.

    return np.array(outputs, dtype=np.int32).reshape(4, 4)

# ====== 입력 로드 (96-cycle) ======
c1_stream = read_hex12_signed(C1_IN_96, n=96)
c2_stream = read_hex12_signed(C2_IN_96, n=96)
c3_stream = read_hex12_signed(C3_IN_96, n=96)

# ====== pool2 연산 (RTL FSM 1:1 에뮬레이션) ======
pool2_outs = []
pool2_outs.append( rtl_fsm_maxpool_relu(c1_stream) ) # (4, 4)
pool2_outs.append( rtl_fsm_maxpool_relu(c2_stream) ) # (4, 4)
pool2_outs.append( rtl_fsm_maxpool_relu(c3_stream) ) # (4, 4)

# ====== pool2 출력 저장 ======
write_hex12_2s(O1_POOL2, pool2_outs[0])
write_hex12_2s(O2_POOL2, pool2_outs[1])
write_hex12_2s(O3_POOL2, pool2_outs[2])

print("[OK] pool2 outputs (4x4) saved (RTL FSM Emulated):")
print(" -", O1_POOL2)
print(" -", O2_POOL2)
print(" -", O3_POOL2)
print("\n[INFO] 96-cycle 입력 파일:", C1_IN_96.name, C2_IN_96.name, C3_IN_96.name)

import json
from pathlib import Path
import numpy as np
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

# ====== 경로 설정 (스크립트의 실행 환경에 맞게 수정 필요) ======
# [!] 이전 스크립트(conv1)의 출력 경로와 일치해야 합니다.
IN_DIR = Path("runs")
# [!] 훈련된 conv2/fc 가중치가 있는 경로로 수정하세요
WDIR = Path("runs/mnist_twn_qat_v4_precision") # weights_txt 폴더로 경로 변경
OUT_DIR = Path("runs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# conv1 출력 경로 (현재 스크립트에서는 로드하지 않으나, RTL 검증 경로에 필요)
C1_O1 = IN_DIR/"conv1_out_ch1_24x24_12b.hex"
C1_O2 = IN_DIR/"conv1_out_ch2_24x24_12b.hex"
C1_O3 = IN_DIR/"conv1_out_ch3_24x24_12b.hex"

# conv2 가중치 파일 (Ternary: -1/0/+1, 각 25개, int8 2's comp HEX)
W_FILES = [
    [WDIR/"conv2_weight_11.txt", WDIR/"conv2_weight_12.txt", WDIR/"conv2_weight_13.txt"], # OC=1
    [WDIR/"conv2_weight_21.txt", WDIR/"conv2_weight_22.txt", WDIR/"conv2_weight_23.txt"], # OC=2
    [WDIR/"conv2_weight_31.txt", WDIR/"conv2_weight_32.txt", WDIR/"conv2_weight_33.txt"], # OC=3
]
# conv2 스케일/바이어스 (int8 2's comp HEX, Q2.6 포맷)
ALPHA_P = WDIR/"conv2_alpha.txt"
BIAS_P  = WDIR/"conv2_bias.txt"

# conv2 출력 파일 (8x8, 12-bit 2's comp HEX)
O1 = OUT_DIR/"conv2_out_ch1_8x8_12b.hex"
O2 = OUT_DIR/"conv2_out_ch2_8x8_12b.hex"
O3 = OUT_DIR/"conv2_out_ch3_8x8_12b.hex"

# FC 가중치 파일
FC_W_P = WDIR/"fc_weight.txt" # 480개 Ternary (-1/0/+1)
FC_B_P = WDIR/"fc_bias.txt"   # 10개 Bias (Q2.6)
FC_S_P = WDIR/"fc_scale.txt"  # 10개 Alpha (Q2.6)

# [FIX] RTL 내부 정밀도 정의
CONV2_ACCUM_BITS = 22
FC_ACCUM_BITS    = 28

# 최종 12비트 포화
SAT_MIN = -2048
SAT_MAX = 2047
ROUND_TERNARY = 32 # 1 << (6 - 1)

# ====== 헬퍼 (RTL 경로) ======
def read_hex12_signed(path, wh=None):
    """ 12-bit 2's complement HEX 파일을 읽어 signed int32 numpy 배열로 반환 """
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFFF
            if v >= 0x800: v -= 0x1000 # 12-bit 2's complement
            vals.append(v)
    a = np.array(vals, dtype=np.int32)
    if wh is not None:
        H,W = wh
        assert a.size == H*W, f"Expected {H}x{W}, got {a.size}"
        a = a.reshape(H,W)
    return a

def read_hex8_signed(path, n=None):
    """ 8-bit 2's complement HEX 파일을 읽어 signed int32 numpy 배열로 반환 """
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFF
            if v >= 128: v -= 256
            vals.append(v)
    return np.array(vals if n is None else vals[:n], dtype=np.int32)

def write_hex12_2s(path, arr_hw):
    with open(path, "w") as f:
        for v in arr_hw.reshape(-1):
            v = int(np.clip(v, -2048, 2047))
            if v < 0: v = (v + (1<<12)) & 0xFFF
            f.write(f"{v:03X}\n")

def im2col5x5_stride1(img):
    # img: HxW -> ( (H-4)*(W-4), 25)
    H,W = img.shape
    out=[]
    OH = H - 5 + 1
    OW = W - 5 + 1
    for y in range(OH):
        for x in range(OW):
            patch = img[y:y+5, x:x+5].reshape(-1).astype(np.int32)
            out.append(patch)
    return np.stack(out, axis=0) # (OH*OW, 25)

def sat12_np(a):
    """ NumPy 배열에 12비트 포화 (SAT_MIN/MAX) 적용 """
    return np.clip(a, SAT_MIN, SAT_MAX).astype(np.int32)

def maxpool_2x2_relu(img_map_in_hw):
    """ RTL의 maxpool_relu 모듈  (2x2 풀링 + ReLU)을 정확히 모델링 """
    H_in, W_in = img_map_in_hw.shape
    assert H_in % 2 == 0 and W_in % 2 == 0, "입력 크기는 짝수여야 합니다."
    H_out, W_out = H_in // 2, W_in // 2
    img_map_out = np.zeros((H_out, W_out), dtype=np.int32)

    for y in range(H_out):
        for x in range(W_out):
            y_in, x_in = y*2, x*2
            # 2x2 윈도우에서 max 찾기
            p1 = img_map_in_hw[y_in,     x_in]
            p2 = img_map_in_hw[y_in,     x_in + 1]
            p3 = img_map_in_hw[y_in + 1, x_in]
            p4 = img_map_in_hw[y_in + 1, x_in + 1]
            max_val = np.max([p1, p2, p3, p4])

            # ReLU 적용
            relu_val = max_val if max_val > 0 else 0
            img_map_out[y, x] = relu_val

    return img_map_out

def q2p6_round_shift(x_int):
    """ RTL의 Q2.6 라운딩 시프트 (alpha, bias 공통)
        (x + 32) >> 6 (ROUND_TERNARY = 32)
    """
    return (x_int + ROUND_TERNARY) >> 6

# [새로운 함수] FC 로짓 계산 및 출력
# ----------------------------------------------------
def calculate_fc_logits(x_flat_fc_input, save_dir="runs/rtl_check_dump"):
    """ FC Layer RTL 경로 연산 시뮬레이션 및 가중치 출력 """
    OUT_DIR = Path(save_dir); OUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1. FC 가중치/스케일 로드 및 변환
    W_fc_flat = read_hex8_signed(FC_W_P)
    W_fc = W_fc_flat.reshape(10, 48)     # (OC=10, IC=48)

    biases_fc_q26 = read_hex8_signed(FC_B_P, n=10)
    alphas_fc_q26 = read_hex8_signed(FC_S_P, n=10)

    biases_fc_int = q2p6_round_shift(biases_fc_q26.astype(np.int64))
    alphas_fc_int = alphas_fc_q26.astype(np.int64)
    X_fc = x_flat_fc_input.astype(np.int64) # (48,)

    # ----------------------------------------------------
    ## 🚀 FC 가중치 행렬 (10x48) 출력 추가
    # ----------------------------------------------------
    print("\n" + "="*70)
    print(" 🚀 FC Weight Matrix (W_fc: 10x48, Ternary: -1/0/+1)")
    print("   [OC=Row (0-9), IC=Column (0-47)]")
    print("="*70)

    # NumPy 설정: 모든 요소를 출력하고, 값 앞에 부호를 표시하여 -1/0/+1 구분이 쉽도록 합니다.
    # W_fc는 10x48 행렬입니다.
    # np.set_printoptions(linewidth=150, threshold=480, formatter={'all': lambda x: f'{x:+2d}'})
    # print(W_fc)
    # np.set_printoptions(formatter=None) # 설정 초기화

    # 행 단위로 출력하여 가독성 높이기
    for oc in range(W_fc.shape[0]):
        # +1, 0, -1을 +1,  0, -1 형태로 출력 (2자리 고정)
        row_str = " ".join(f"{v:+2d}" for v in W_fc[oc].tolist())
        print(f"OC {oc:02d}: {row_str}")

    print("="*70 + "\n")
    # ----------------------------------------------------

    # 2. FC 연산 (Dot Product)
    psum_raw_fc = np.zeros(10, dtype=np.int64)

    for oc in range(10):
        W_oc = W_fc[oc]

        # Ternary MAC 로직 (기존 코드 유지)
        ternary_mul_fc = np.where(W_oc == 1, X_fc, np.where(W_oc == -1, -X_fc, 0))
        psum_raw_oc = np.sum(ternary_mul_fc)
        psum_raw_fc[oc] = psum_raw_oc

    # 3. α 스케일링 + Bias 덧셈 + Saturation
    ACC_MIN_FC = -(1 << (FC_ACCUM_BITS - 1))
    ACC_MAX_FC = (1 << (FC_ACCUM_BITS - 1)) - 1
    psum_fc_sat = np.clip(psum_raw_fc, ACC_MIN_FC, ACC_MAX_FC)

    m_a_fc = psum_fc_sat * alphas_fc_int
    scaled_fc = q2p6_round_shift(m_a_fc)
    summed_fc = scaled_fc + biases_fc_int

    # 최종 12-bit 포화 (Logits)
    logits_fc = sat12_np(summed_fc)

    print("\n" + "="*40)
    print("   FC Layer Output (Logits)")
    print("="*40)
    print("Raw Psum (before scaling/saturation):")
    print(psum_raw_fc)
    print("\nFinal Logits (12-bit Integer):")
    print(logits_fc)
    print(f"\nPredicted Class (Max Index): {np.argmax(logits_fc)}")

    # HEX 출력
    print_hex12_2s_console(logits_fc)

    # 파일 저장
    LOGITS_P = OUT_DIR/"fc_logits_10x1_12b.hex"
    write_hex12_2s(LOGITS_P, logits_fc)
    print(f"\n[OK] FC Logits saved to: {LOGITS_P}")

    return logits_fc

# ====== Main Execution ======

# ====== 1. conv1 출력 로드 (24x24) ======
c1_out_maps = [
    read_hex12_signed(C1_O1, wh=(24,24)),
    read_hex12_signed(C1_O2, wh=(24,24)),
    read_hex12_signed(C1_O3, wh=(24,24))
]

# ====== 2. MaxPool + ReLU (1) ======
pool1_out_maps = [maxpool_2x2_relu(m) for m in c1_out_maps] # 3x (12, 12)

# ====== 3. conv2_buf (im2col) ======
cols_all_ic = np.stack([im2col5x5_stride1(m) for m in pool1_out_maps], axis=0)

# ====== 4. conv2 가중치/스케일/바이어스 로드 ======
W_conv2 = np.zeros((3, 3, 25), dtype=np.int32) # (oc, ic, tap)
for oc in range(3):
    for ic in range(3):
        W_conv2[oc, ic] = read_hex8_signed(W_FILES[oc][ic], n=25)

biases_q26  = read_hex8_signed(BIAS_P,  n=3)
alphas_q26  = read_hex8_signed(ALPHA_P, n=3)

biases_int = q2p6_round_shift(biases_q26.astype(np.int64))

# ====== 5. conv2 연산 (RTL 정수 경로 그대로) ======
outs_conv2 = []
for oc in range(3):
    W_oc = W_conv2[oc]
    A_oc = np.int64(alphas_q26[oc])
    B_oc = np.int64(biases_int[oc])

    psum_raw_per_patch = np.zeros(64, dtype=np.int64)

    for ic in range(3):
        x_ic = cols_all_ic[ic]
        w_ic = W_oc[ic]

        ternary_mul = np.where(w_ic == 1, x_ic, np.where(w_ic == -1, -x_ic, 0))

        sum_ic = np.sum(ternary_mul, axis=1)

        psum_raw_per_patch += sum_ic

    m_a = psum_raw_per_patch * A_oc
    scaled = q2p6_round_shift(m_a)
    summed = scaled + B_oc
    saturated = sat12_np(summed)
    outs_conv2.append(saturated.reshape(8, 8))

# ====== 6. 저장 (8x8) ======
write_hex12_2s(O1, outs_conv2[0])
write_hex12_2s(O2, outs_conv2[1])
write_hex12_2s(O3, outs_conv2[2])

print("[OK] conv2 outputs (8x8) saved:")
print(" -", O1)
print(" -", O2)
print(" -", O3)
print(f"\n[INFO] maxpool_relu(1) inputs (24x24) loaded from:")
print(" -", C1_O1.name)
print(" -", C1_O2.name)
print(" -", C1_O3.name)

# ====== 7. [추가] MaxPool + ReLU (2) (8x8 -> 4x4) ======

pool2_out_maps = [maxpool_2x2_relu(m) for m in outs_conv2] # 3x (4, 4)

# --- 파일로 저장 (FC 스크립트의 입력이 됨) ---
P2_O1 = OUT_DIR/"pool2_out_ch1_4x4_12b.hex"
P2_O2 = OUT_DIR/"pool2_out_ch2_4x4_12b.hex"
P2_O3 = OUT_DIR/"pool2_out_ch3_4x4_12b.hex"

write_hex12_2s(P2_O1, pool2_out_maps[0])
write_hex12_2s(P2_O2, pool2_out_maps[1])
write_hex12_2s(P2_O3, pool2_out_maps[2])

print("[OK] pool2 outputs (4x4) saved:")
print(f" - {P2_O1.name}")
print(f" - {P2_O2.name}")
print(f" - {P2_O3.name}")

# --- 콘솔에 값 출력 ---
print("\n--- Channel 1 (4x4) ---")
print(pool2_out_maps[0])

print("\n--- Channel 2 (4x4) ---")
print(pool2_out_maps[1])

print("\n--- Channel 3 (4x4) ---")
print(pool2_out_maps[2])

# --- FC 계층 입력 (Flatten) ---
x_flat_fc_input = np.concatenate([m.flatten() for m in pool2_out_maps])

print("\n" + "="*40)
print("   Flattened FC Input (48 values)")
print("="*40)
print(x_flat_fc_input)
print(f"\nShape: {x_flat_fc_input.shape}")

# --- [추가] HEX 값 출력 ---
print_hex12_2s_console(x_flat_fc_input)

# ====== 8. [추가] FC 로짓 계산 및 출력 ======
calculate_fc_logits(x_flat_fc_input)

import numpy as np
from pathlib import Path
import os

# ===== 경로 설정 (제시된 경로 사용) =====
IN_DIR = Path("runs")
WDIR = Path("runs/mnist_twn_qat_v4_precision")
OUT_DIR = Path("runs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# CONV1/POOL1 출력이 저장된 파일 경로 (현재 코드 블록에 있음)
C1_O1 = IN_DIR/"conv1_out_ch1_24x24_12b.hex"
C1_O2 = IN_DIR/"conv1_out_ch2_24x24_12b.hex"
C1_O3 = IN_DIR/"conv1_out_ch3_24x24_12b.hex"

# CONV2 가중치/스케일 파일 경로
W_FILES = [
    [WDIR/"conv2_weight_11.txt", WDIR/"conv2_weight_12.txt", WDIR/"conv2_weight_13.txt"],
    [WDIR/"conv2_weight_21.txt", WDIR/"conv2_weight_22.txt", WDIR/"conv2_weight_23.txt"],
    [WDIR/"conv2_weight_31.txt", WDIR/"conv2_weight_32.txt", WDIR/"conv2_weight_33.txt"],
]
ALPHA_P = WDIR/"conv2_alpha.txt"
BIAS_P  = WDIR/"conv2_bias.txt"

# [출력] RTL Cycle 순서 덤프 파일 (64 Cycles * 3 Channels = 192 값)
CONV2_DUMP_FILE = OUT_DIR/"conv2_output_64_cycles_rtl_flow.txt"


# ====== 헬퍼 함수 (제시된 코드 블록에서 정의됨) ======
# 필요한 함수들을 이전 코드에서 가져옵니다.

def read_hex12_signed(path, wh=None):
    # ... (read_hex12_signed 함수 정의) ...
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFFF
            if v >= 0x800: v -= 0x1000
            vals.append(v)
    a = np.array(vals, dtype=np.int32)
    if wh is not None:
        H,W = wh
        if a.size != H*W:
             raise ValueError(f"Expected {H}x{W} ({H*W} elements), got {a.size} in {path.name}")
        a = a.reshape(H,W)
    return a

def read_hex8_signed(path, n=None):
    # ... (read_hex8_signed 함수 정의) ...
    vals=[]
    with open(path) as f:
        for line in f:
            s=line.strip()
            if not s: continue
            v = int(s, 16) & 0xFF
            if v >= 128: v -= 256
            vals.append(v)
    return np.array(vals if n is None else vals[:n], dtype=np.int32)

def im2col5x5_stride1(img):
    # ... (im2col5x5_stride1 함수 정의) ...
    H,W = img.shape
    out=[]
    OH = H - 5 + 1
    OW = W - 5 + 1
    for y in range(OH):
        for x in range(OW):
            patch = img[y:y+5, x:x+5].reshape(-1).astype(np.int32)
            out.append(patch)
    return np.stack(out, axis=0)

def sat12_np(a):
    # ... (sat12_np 함수 정의) ...
    return np.clip(a, -2048, 2047).astype(np.int32)

def maxpool_2x2_relu(img_map_in_hw):
    # ... (maxpool_2x2_relu 함수 정의) ...
    H_in, W_in = img_map_in_hw.shape
    H_out, W_out = H_in // 2, W_in // 2
    img_map_out = np.zeros((H_out, W_out), dtype=np.int32)
    for y in range(H_out):
        for x in range(W_out):
            y_in, x_in = y*2, x*2
            p1 = img_map_in_hw[y_in, x_in]
            p2 = img_map_in_hw[y_in, x_in + 1]
            p3 = img_map_in_hw[y_in + 1, x_in]
            p4 = img_map_in_hw[y_in + 1, x_in + 1]
            max_val = np.max([p1, p2, p3, p4])
            img_map_out[y, x] = max_val if max_val > 0 else 0
    return img_map_out

def q2p6_round_shift(x_int):
    # ... (q2p6_round_shift 함수 정의) ...
    return (x_int + 32) >> 6

# ====== 1. 이전 단계 출력 (Conv1 -> Pool1) 로드/계산 ======

# 1-1. Conv1 출력 로드 (24x24)
c1_out_maps = [
    read_hex12_signed(C1_O1, wh=(24,24)),
    read_hex12_signed(C1_O2, wh=(24,24)),
    read_hex12_signed(C1_O3, wh=(24,24))
]

# 1-2. Pool1 연산 (Conv2 입력) (24x24 -> 12x12)
pool1_out_maps = [maxpool_2x2_relu(m) for m in c1_out_maps] # 3x (12, 12)

# 1-3. im2col 변환 (Conv2 Buffer 역할)
# (ic, patch_idx, tap) -> (3, 64, 25)
cols_all_ic = np.stack([im2col5x5_stride1(m) for m in pool1_out_maps], axis=0)
NUM_CYCLES = cols_all_ic.shape[1] # 64 cycles

# ====== 2. Conv2 가중치/스케일/바이어스 로드 ======
W_conv2 = np.zeros((3, 3, 25), dtype=np.int32) # (oc, ic, tap)
for oc in range(3):
    for ic in range(3):
        # W_FILES 경로는 상위 스코프에 정의되어 있음
        W_conv2[oc, ic] = read_hex8_signed(W_FILES[oc][ic], n=25)

biases_q26  = read_hex8_signed(BIAS_P,  n=3)
alphas_q26  = read_hex8_signed(ALPHA_P, n=3)
biases_int = q2p6_round_shift(biases_q26.astype(np.int64))


# ====== 3. CONV2 연산 및 RTL Cycle Dump (64 Cycles) ======

print(f"\n[INFO] Starting CONV2 RTL Cycle Dump (Total {NUM_CYCLES} Cycles)")
print(f"       Saving output to: {CONV2_DUMP_FILE.name}\n")

rtl_dump_sequence = []
with open(CONV2_DUMP_FILE, "w") as f_dump:

    # Cycle (Patch Index) Loop: 0 to 63 (RTL clock cycles)
    for p_idx in range(NUM_CYCLES):

        cycle_outputs = np.zeros(3, dtype=np.int64)

        # Output Channel Loop: OC=0, 1, 2
        for oc in range(3):
            W_oc = W_conv2[oc]
            A_oc = np.int64(alphas_q26[oc])
            B_oc = np.int64(biases_int[oc])

            # 1. Input Channel Summation (IC=0, 1, 2)
            psum_raw = np.int64(0)
            for ic in range(3):
                x_ic_patch = cols_all_ic[ic, p_idx, :] # 25 Taps
                w_ic_tap   = W_oc[ic, :]

                # [RTL Ternary MAC]
                ternary_mul = np.where(w_ic_tap == 1, x_ic_patch,
                                       np.where(w_ic_tap == -1, -x_ic_patch, 0))

                # [3-Channel Summation] psum_raw = sum(sum_ic)
                psum_raw += np.sum(ternary_mul) # Accumulator Tree Sum

            # --- α 스케일링 + Bias 덧셈 + Saturation ---

            m_a = psum_raw * A_oc
            scaled = q2p6_round_shift(m_a)
            summed = scaled + B_oc

            # 12-bit 포화 (signed [-2048, 2047])
            saturated = sat12_np(summed)

            cycle_outputs[oc] = saturated

        # 4. Dump (C1, C2, C3 순서)
        for val in cycle_outputs:
            v_clip = int(np.clip(val, -2048, 2047))

            # 12-bit 2's complement HEX 변환
            if v_clip < 0:
                v_hex = (v_clip + (1<<12)) & 0xFFF
            else:
                v_hex = v_clip

            f_dump.write(f"{v_hex:03X}\n")
            rtl_dump_sequence.append(v_clip)

        # 96 Cycle 제한은 64 Cycle이 최대이므로 무시하고 64에서 종료

print(f"[OK] CONV2 RTL Cycle Dump ({NUM_CYCLES} Cycles) saved: {CONV2_DUMP_FILE.name}")
print(f"     Total {len(rtl_dump_sequence)} values (12-bit signed) written.")

print("\n--- 첫 10 Cycle (30 값) 미리보기 (RTL 파형 C1, C2, C3 순서) ---")
for i in range(10):
    start = i * 3
    print(f"Cycle {i:02d}: C1={rtl_dump_sequence[start]:5d}, C2={rtl_dump_sequence[start+1]:5d}, C3={rtl_dump_sequence[start+2]:5d}")

# 다음 검증 단계: RTL 시뮬레이션에서 이 시퀀스가 conv2_out_1, conv2_out_2, conv2_out_3 순서로 64번 출력되는지 확인하세요.

# reverse_per_48.py
from pathlib import Path

IN  = Path("runs/mnist_twn_qat_v4_precision/fc_weight.txt")     # 여기에 네가 붙여넣은 리스트 저장
OUT = Path("fc_weight_out.txt")

LINES_PER_NEURON = 48
NEURONS = 10  # 10개 묶음 순서는 유지

# 읽기 (빈 줄 제외)
lines = [ln.strip() for ln in IN.read_text().splitlines() if ln.strip()]
assert len(lines) % LINES_PER_NEURON == 0, f"line count {len(lines)} not multiple of {LINES_PER_NEURON}"
assert len(lines) == NEURONS * LINES_PER_NEURON, f"expect {NEURONS*LINES_PER_NEURON} lines, got {len(lines)}"

out = []
for n in range(NEURONS):
    base = n * LINES_PER_NEURON
    block = lines[base:base+LINES_PER_NEURON]
    out.extend(block[::-1])  # ← 48줄 블록만 역순

OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"[OK] wrote: {OUT} ({len(out)} lines)")

# reverse_block_order_final.py

from pathlib import Path

# *****************************************************************
# ⚠️ 주의: 입력 파일 경로를 실제 환경에 맞게 정확히 지정해야 합니다.
# 두 번째 정의된 경로를 사용합니다.
IN = Path("runs/mnist_twn_qat_v4_precision/fc_weight.txt")
# *****************************************************************

OUT = Path("fc_weight_block_reversed.txt")

LINES_PER_BLOCK = 48
TOTAL_BLOCKS = 10
TOTAL_LINES = TOTAL_BLOCKS * LINES_PER_BLOCK # 480줄

def reverse_blocks():
    """
    입력 파일을 읽어 48줄 블록 10개의 순서를 역순으로 뒤집고,
    그 결과를 새 파일에 저장합니다.
    """
    try:
        # 파일 읽기 (빈 줄 제거)
        lines = [ln.strip() for ln in IN.read_text(encoding="utf-8").splitlines() if ln.strip()]
    except FileNotFoundError:
        # 이 오류는 사용자의 파일 시스템 문제이므로, 경로 확인이 필요합니다.
        return f"🚨 오류: 입력 파일 '{IN}'을 찾을 수 없습니다. 파일 경로가 정확한지 확인해 주세요."
    except Exception as e:
        return f"⚠️ 오류: 파일을 읽는 중 문제가 발생했습니다: {e}"

    # 데이터 길이 확인 (480줄 확인)
    if len(lines) != TOTAL_LINES:
        return f"❌ 오류: 파일의 줄 수가 {TOTAL_LINES}줄이어야 하는데, 현재 {len(lines)}줄입니다."

    # 1. 48줄씩 10개의 블록으로 분리
    blocks = []
    for i in range(0, len(lines), LINES_PER_BLOCK):
        blocks.append(lines[i:i + LINES_PER_BLOCK])

    # 2. 블록 자체의 순서를 역순으로 뒤집기 (요청하신 작업: [B10, B9, ..., B1])
    reversed_blocks = blocks[::-1]

    # 3. 뒤집힌 블록을 다시 하나의 리스트로 결합
    out = []
    for block in reversed_blocks:
        out.extend(block)

    # 4. 파일 쓰기
    try:
        # 마지막에 빈 줄을 추가하여 파일 쓰기 완료
        OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
        return f"✅ 성공: 파일에 성공적으로 저장되었습니다: {OUT} (총 {len(out)} lines)"
    except Exception as e:
        return f"⚠️ 오류: 파일을 쓰는 중 문제가 발생했습니다: {e}"

# --- 이 함수를 파이썬 환경에서 실행하세요 ---
# print(reverse_blocks())

if __name__ == "__main__":
    result_message = reverse_blocks()
    print(result_message)